exclude: "^src/bitbirch/"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: ^docs/
      - id: end-of-file-fixer
        exclude: ^docs/
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: detect-private-key
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: debug-statements
      - id: check-ast

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        args: ["--write"]
        # Only run prettier on TOML and YAML files for this project
        files: '\\.(toml|ya?ml)$'

  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        name: Strip Notebook Outputs
        entry: nbstripout --keep-output-metadata --strip-newlines
        language: python
        files: '\\.(ipynb)$'

  - repo: local
    hooks:
      # - id: rebuild-docs
      #   name: rebuild docs
      #   entry: scripts/infra/rebuild-docs-precommit.sh
      #   language: system
      #   pass_filenames: false
      #   stages: [pre-commit]

      - id: beautysh
        name: beautify shell scripts
        entry: shfmt -w -i 2
        language: system
        types: [shell]

      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        exclude: ^docs/

      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        exclude: ^docs/

      - id: flake8
        name: flake8
        entry: flake8 src tests
        language: system
        types: [python]
        exclude: ^(docs/|notebooks/)

      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        exclude: ^(docs/|notebooks/|tests/)
        args: ["--fail-under=9.0"]

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        exclude: ^(docs/|notebooks/|tests/|archive/|src/bitbirch/)

      - id: pytest
        name: pytest
        entry: pytest -n auto -q -m "not no_mlflow_runs"
        language: system
        pass_filenames: false

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
    hooks:
      - id: commitizen
        name: commitizen check
        entry: cz check
        language: python
        stages: [commit-msg]
